import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { checkout } from "../checkout";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>BUY MY SERVICES</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>BUY MY SERVICES</h1>
				<Image src="/images/developer.jpg" alt="pic" width={800} height={400} />

				<div className={styles.grid}>
					<div>
						<h2>WEB DESIGN &rarr;</h2>
						<p>From $2000 onwards</p>
						<button
							onClick={() => {
								checkout({
									lineItems: [
										{
											price: "price_1L8CCwHbqsTPJ09lse2nHmeE",
											quantity: 1,
										},
									],
								});
							}}
						>
							BUY
						</button>
					</div>

					<a href="https://nextjs.org/learn" className={styles.card}>
						<h2>IOS DESIGN &rarr;</h2>
						<p>From $5000 onwards</p>
					</a>

					<a
						href="https://github.com/vercel/next.js/tree/canary/examples"
						className={styles.card}
					>
						<h2>TEMPLATE DESIGN &rarr;</h2>
						<p>From $1000 onwards</p>
					</a>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
					>
						<h2>COMING SOON! &rarr;</h2>
						<p>GO GREEN!</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
